name: "Import / Export Helfer"
version: "v20251107.1623"
slug: "import_export_helfer"
description: "Sichert und stellt einzelne Home Assistant Elemente (Helfer, YAML, etc.) wieder her."
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
startup: "application"
boot: "auto"
init: false
ingress: true
panel_icon: "mdi:archive"
webui: "http://[HOST]:[PORT:8099]"
map:
  - "config:rw"
hassio_api: true
hassio_role: "admin"
ports:
  "8099/tcp": null
schema: {}
